site_name: Archway
theme: readthedocs
pages:
  - index.md
  - workspace_creation.md
  - workspace_management.md
  - installation.md
  - changelog.md
  - cloudera.md
  - contributing.md
  - development.md
  - introduction.md
  - releases.md
  - service.md
  - architecture.md
